---
- name: Temporary directory
  file:
    path: "{{ linuxbrew_install_tmp }}"
    state: directory

- name: Download linuxbrew install script
  get_url:
    url: "{{ linuxbrew_install_url }}"
    dest: "{{ linuxbrew_install_tmp }}/install.sh"
    mode: 0777

- name: Install linuxbrew
  command: sh -c "NONINTERACTIVE=1 {{ linuxbrew_install_tmp }}/install.sh"
  register: install_result
  changed_when: "install_result.rc == 0"

- name: Update linuxbrew
  command: sh -c "/home/linuxbrew/.linuxbrew/bin/brew upgrade --force --quite"

- name: Remove temporary directory
  file:
    path: "{{ linuxbrew_install_tmp }}"
    state: absent
